In [5]:
from sklearn.model_selection import KFold
import numpy as np

seed=0
n_fold = 10
skf = KFold(n_splits=n_fold, shuffle = True, random_state=seed)

n_samples = 20
X = np.arange(n_samples)

k = 10
kf = KFold(n_splits=k, shuffle = False)
for train_index, test_index in kf.split(X):
    print(train_index, "\t", test_index)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] 	 [0 1]
[ 0  1  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] 	 [2 3]
[ 0  1  2  3  6  7  8  9 10 11 12 13 14 15 16 17 18 19] 	 [4 5]
[ 0  1  2  3  4  5  8  9 10 11 12 13 14 15 16 17 18 19] 	 [6 7]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 18 19] 	 [8 9]
[ 0  1  2  3  4  5  6  7  8  9 12 13 14 15 16 17 18 19] 	 [10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11 14 15 16 17 18 19] 	 [12 13]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 16 17 18 19] 	 [14 15]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 18 19] 	 [16 17]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17] 	 [18 19]


In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold
import pandas as pd
import numpy as np

seed = 0 
np.random.seed(seed)
tf.random.set_seed(seed)
df = pd.read_csv('sonar.csv', header = None)
dataset = df.values
X = dataset[:,0:60]
y = dataset[:, 60]
e = LabelEncoder()
e.fit(y)
Y = e.transform(y)

n_fold = 10
skf = StratifiedKFold(n_splits=n_fold, shuffle=True, random_state = seed)

accuracy = []

for train, test in skf.split(X, Y):
    model = Sequential()
    model.add(Dense(24, input_dim = 60, activation = 'relu'))
    model.add(Dense(10, activation = 'relu'))
    model.add(Dense(1, activation = 'sigmoid'))
    model.compile(loss='binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

    X_train = tf.convert_to_tensor(X[train],  dtype=tf.float32)
    Y_train = tf.convert_to_tensor(Y[train],  dtype=tf.float32)
    model.fit(X_train, Y_train, epochs=100, batch_size=5)
    X_test =  tf.convert_to_tensor(X[test],  dtype=tf.float32)
    Y_test =  tf.convert_to_tensor(Y[test],  dtype=tf.float32)
    k_accuracy = "%.4f" %(model.evaluate(X_test, Y_test)[1])
    accuracy.append(k_accuracy)

print(n_fold, accuracy)

Epoch 1/100


/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


38/38 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5188 - loss: 0.6978
Epoch 2/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6575 - loss: 0.6572
Epoch 3/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6962 - loss: 0.6432
Epoch 4/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7379 - loss: 0.6227
Epoch 5/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7701 - loss: 0.5976
Epoch 6/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7669 - loss: 0.5750
Epoch 7/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7657 - loss: 0.5535
Epoch 8/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7734 - loss: 0.5330
Epoch 9/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7637 - loss: 0.5154
Epoch 10/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7637 - loss: 0.4990
Epoch 11/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7717 - loss: 0.4841
Epoch 12/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7413 - lo

In [ ]:
import os
from tensorflow.keras.callbacks  import ModelCheckpoint, EarlyStopping
import matplotlib.pyplot as plt

df_pre = pd.read_csv("wine.csv", header=None)
df = df_pre.sample(frac = 1)

dataset2 = df.values
x = dataset2[:, 0:12]
y = dataset2[:, 12]

model = Sequential()
model.add(Dense(30, input_dim=12, activation='relu'))
model.add(Dense(12, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])


MODEL_DIR ='./model/'
if not os.path.exists(MODEL_DIR):
    os.mkdir(MODEL_DIR)

early_stoppping_callback = EarlyStopping(monitor='val_loss', patience = 100)

modelpath="./model/{epoch:02d}-{val_loss:.4f}.keras"
checkpointer = ModelCheckpoint(filepath = modelpath, monitor='val_loss', verbose=1, save_best_only=True)


#model.fit(x, y, validation_split=0.2, epochs=200, batch_size = 200, verbose=0, callbacks=[checkpointer])
history = model.fit(x, y, validation_split=0.33, epochs=3500, batch_size=500, callbacks=[early_stoppping_callback, checkpointer])
y_vloss = history.history['val_loss']
y_acc=history.history['accuracy']
y_vacc = history.history['val_accuracy']
y_loss = history.history['loss']

x_len = np.arange(len(y_acc))
plt.plot(x_len, y_vloss, "o", c="red", markersize=2)
plt.plot (x_len, y_acc, "o", c="blue", markersize=2)
plt.plot (x_len, y_vacc, "o", c="pink", markersize=2)
plt.plot (x_len, y_loss, "o", c="green", markersize=2)
plt.show()

print("accuracy: ", model.evaluate(x, y)[1])

Epoch 1/3500


/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/9 ━━━━━━━━━━━━━━━━━━━━ 12s 2s/step - accuracy: 0.7740 - loss: 1.5625
Epoch 1: val_loss improved from inf to 0.96440, saving model to ./model/01-0.9644.keras
9/9 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - accuracy: 0.7563 - loss: 1.4810 - val_accuracy: 0.7492 - val_loss: 0.9644
Epoch 2/3500
1/9 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.7740 - loss: 0.8027
Epoch 2: val_loss improved from 0.96440 to 0.35056, saving model to ./model/02-0.3506.keras
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7632 - loss: 0.7114 - val_accuracy: 0.8508 - val_loss: 0.3506
Epoch 3/3500
1/9 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8520 - loss: 0.3261
Epoch 3: val_loss improved from 0.35056 to 0.33037, saving model to ./model/03-0.3304.keras
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8541 - loss: 0.3838 - val_accuracy: 0.8531 - val_loss: 0.3304
Epoch 4/3500
1/9 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.8680 - loss: 0.2942
Epoch 4: val_loss did not improve from 0.33037
9/9 ━━━━━━━━━

In [19]:
import tensorflow as tf
from tensorflow.keras.models import load_model
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

df = pd.read_csv('wine.csv', header =None)
dataset = df.values

X = dataset[:, 0:12]
Y = dataset[:, 12]

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

model=load_model('./model/1644-0.0309.keras')

loss, accuracy = model.evaluate(X_test, Y_test)
print(f'Loss: {loss}')
print(f'Accuracy: {accuracy}')

new_data = pd.DataFrame({
    'fixed acidity': [7.4, 7.8, 7.8, 11.2, 7.4, 6.2, 6.6, 6.5, 5.5, 6.0],
    'volatile acidity': [0.7, 0.88, 0.76, 0.28, 0.7, 0.21, 0.32, 0.24, 0.29, 0.21],
    'citric acid': [0, 0, 0.04, 0.56, 0, 0.29, 0.36, 0.19, 0.3, 0.38],
    'residual sugar': [1.9, 2.6, 2.3, 1.9, 1.9, 1.6, 8, 1.2, 1.1, 0.8],
    'chlorides': [0.076, 0.098, 0.092, 0.075, 0.076, 0.039, 0.047, 0.041, 0.022, 0.02],
    'free sulfur dioxide': [11, 25, 15, 17, 11, 24, 57, 30, 20, 22],
    'total sulfur dioxide': [34, 67, 54, 60, 34, 92, 168, 111, 110, 98],
    'density': [0.9978, 0.9968, 0.997, 0.998, 0.9978, 0.99114, 0.9949, 0.99254, 0.98869, 0.98941],
    'pH': [3.51, 3.2, 3.26, 3.16, 3.51, 3.27, 3.15, 2.99, 3.34, 3.26],
    'sulphates': [0.56, 0.68, 0.65, 0.58, 0.56, 0.5, 0.46, 0.46, 0.38, 0.32],
    'alcohol': [9.4, 9.8, 9.8, 9.8, 9.4, 11.2, 9.6, 9.4, 12.8, 11.8],
    'taste': [5, 5, 5, 6, 5, 6, 5, 6, 7, 6],
    'quality': [1, 1, 1, 1, 1, 0, 0, 0, 0, 0]  # 실제 구분 등급인 quality 값을 추가(확인용)
})

actual_quality=new_data['quality'].values
new_data = new_data.drop('quality', axis=1).values

predictions = model.predict(new_data)
print('Predictions:', predictions)
predictions = (predictions >0.5).astype(int).flatten()

accuracy = np.mean(predictions == actual_quality)
print('Predictions:', predictions)
print('Actual:', actual_quality)
print(f'Accuracy: {accuracy * 100:.2f}%')


41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9951 - loss: 0.0139 
Loss: 0.017507249489426613
Accuracy: 0.9938461780548096
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step
Predictions: [[9.9999899e-01]
 [1.0000000e+00]
 [1.0000000e+00]
 [9.9986446e-01]
 [9.9999899e-01]
 [5.3148596e-03]
 [1.7220490e-03]
 [4.4893997e-04]
 [1.7968524e-02]
 [3.8684926e-03]]
Predictions: [1 1 1 1 1 0 0 0 0 0]
Actual: [1 1 1 1 1 0 0 0 0 0]
Accuracy: 100.00%
