In [3]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])

print(a[1:4])
print(a)

b=a[1:4]
b[0] = 99

print("2b", b)
print(a)

b[0] = 2
print(a)

c = a[1:4].copy()
c[0] = 99
print("c", c)
print("a", a)



[2 3 4]
[1 2 3 4 5]
2b [99  3  4]
[ 1 99  3  4  5]
[1 2 3 4 5]
c [99  3  4]
a [1 2 3 4 5]


In [11]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import numpy as np

Instructions for updating:
non-resource variables are not supported in the long term


In [39]:
xy = np.loadtxt("data-03-diabetes.csv", delimiter=",", dtype=np.float32)

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print("x_data 5개:\n", x_data[:3])
print("y_data 5개:\n", y_data[:3])

X = tf.placeholder(tf.float32, shape=[None, 8]) #x 두개 짜리 데이터 그릇
Y = tf.placeholder(tf.float32, shape=[None, 1]) #y 한개 짜리 데이터 그릇

w = tf.Variable(tf.random_normal([8, 1], name = 'weight'))
b = tf.Variable(tf.random_normal([1], name = 'bias'))

#y 시그모이드 함수 방정식 사용
hypothesis = tf.sigmoid(tf.matmul(X, w)+ b)

#오차 함수
cost = -tf.reduce_mean(Y*tf.log(hypothesis) + (1 - Y) * tf.log(1-hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate = 0.01).minimize(cost)

#정확도
predicted = tf.cast(hypothesis>0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for i in range(10001):        
        cost_val, _ = sess.run([cost, train], feed_dict = {X: x_data, Y: y_data})
        if i % 200 == 0:
            print(f'step={i}, loss={cost_val}')

    w_l, b_l = sess.run([w,b])
    
    _, _, a = sess.run([hypothesis, predicted, accuracy], feed_dict={X:x_data, Y:y_data})
    
    print("\nAccuracy: ", a)

x_data 5개:
 [[-0.294118    0.487437    0.180328   -0.292929    0.          0.00149028
  -0.53117    -0.0333333 ]
 [-0.882353   -0.145729    0.0819672  -0.414141    0.         -0.207153
  -0.766866   -0.666667  ]
 [-0.0588235   0.839196    0.0491803   0.          0.         -0.305514
  -0.492741   -0.633333  ]]
y_data 5개:
 [[0.]
 [1.]
 [0.]]
step=0, loss=0.9558215737342834
step=200, loss=0.7791823744773865
step=400, loss=0.7336844205856323
step=600, loss=0.7089707851409912
step=800, loss=0.6891480088233948
step=1000, loss=0.6717402935028076
step=1200, loss=0.6561968922615051
step=1400, loss=0.6422688364982605
step=1600, loss=0.629768431186676
step=1800, loss=0.6185320615768433
step=2000, loss=0.6084148287773132
step=2200, loss=0.5992878079414368
step=2400, loss=0.5910375118255615
step=2600, loss=0.5835639834403992
step=2800, loss=0.5767791867256165
step=3000, loss=0.5706057548522949
step=3200, loss=0.5649760961532593
step=3400, loss=0.5598307251930237
step=3600, loss=0.5551175475120544


In [81]:
new_data = np.array([
    [0.882353, -0.105528, 0.0819672, -0.535354, -0.777778, -0.162444, -0.923997, 0],
    [-0.764706,-0.286432,0.147541,-0.454545,0,-0.165425,-0.566183,-0.966667],
    [0.882353, -0.0251256, 0.0819672, -0.69697, -0.669031, -0.308495, -0.650726, -0.966667],
    [0.176471, 0.256281, 0.147541, -0.474747, -0.728132, -0.0730253, -0.891546, -0.333333],
    [-0.647059,0.708543,0.0491803,-0.252525,-0.468085,0.028316,-0.762596,-0.7],
    [0.0588235, 0.718593, 0.803279, -0.515152, -0.432624, 0.353204, -0.450897, 0.1]]
    , dtype=np.float32)

X = new_data.copy()


def sigmoid(z):
    return 1 / (1+ np.exp(-z))


z = np.matmul(X, w_l) + b_l
predicted_prob = sigmoid(z)
predicted_label = (predicted_prob > 0.5).astype(np.int32)

for i in range(len(X)):
    print(f'입력 {i+1}: 예측 = {predicted_label[i][0]}, 확률 = {predicted_prob[i][0]:.4f}')

입력 1: 예측 = 1, 확률 = 0.8095
입력 2: 예측 = 1, 확률 = 0.9181
입력 3: 예측 = 1, 확률 = 0.7024
입력 4: 예측 = 1, 확률 = 0.6586
입력 5: 예측 = 0, 확률 = 0.4595
입력 6: 예측 = 0, 확률 = 0.0921
