What is TensorFlow?
- 

A flow of Tensors, where tensor defines as:
-  n dimensional abstraction of matrics
-  Or simply similar to Numpy Array

In [2]:
import numpy as np

my_list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(type(my_list))
ar = np.array(my_list)
print(type(ar))

<class 'list'>
<class 'numpy.ndarray'>


In [4]:
"""
List Vs np.array

List - handles data
Array - handles calculations
"""

al = [1, 2, 3] #list
bl = [4, 5, 6] #list
aa = np.array(al) #array
ba = np.array(bl) #array

print(al + bl) #list + list will give the append
print(aa + ba) #array + array will give the vector addition

print(al*2) #list * 2 will duplicate and append
print(aa*2) #array * 2 will give vector multiples

print(aa == 2) #array will return individual comparason
print(al == 2) #list will just compare the whole list

[1, 2, 3, 4, 5, 6]
[5 7 9]
[1, 2, 3, 1, 2, 3]
[2 4 6]
[False  True False]
False


In [10]:
c = np.array([[0, 1, 2], [3, 4, 5]]) #2 x 3 array

print(c) # 2 rows, 3 columns
print(len(c)) #row len
print(len(c[0])) #column len
print(c.shape) #shape
print(c.ndim) #dimension

c[0, 0]

[[0 1 2]
 [3 4 5]]
2
3
(2, 3)
2


0

In [12]:
#slicing
a = np.array([[0, 1, 2, 3],[4, 5, 6, 7]])

a[0, :]
a[:, 0:2]
a[:, 1]

array([1, 5])

In [14]:
#array mix with index

a = np.array([0, 1, 2,3,4,5,6,7,8,9])
idx = np.array([True, False, True, False, True, False, True, False, True, False])
print(a[idx])
print(a[a%2==0])

[0 2 4 6 8]
[0 2 4 6 8]


In [18]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8])
print(a[idx])

[11 33 55 77 99]


In [22]:
#dtype


x = np.array([1,2,3])
print(x.dtype)
x = np.array([1.0,2.0,3.0])
print(x.dtype)
x = np.array([1, 2, 3.0])
print(x.dtype)

int64
float64
float64


In [24]:
"""
b boolean
i integer
u u float
f float
c 복소 부동소수점
o object
s byte
u unicode
"""
x = np.array([1, 2, 3], dtype = 'f')
x.dtype
print(x[0] + x[1])

x = np.array([1, 2, 3], dtype =  'U')
x.dtype
print(x[0] + x[1])

3.0
12


In [30]:
# inf : infinity, NaN (Not a Number)
import numpy as np
np.seterr(divide='ignore', invalid='ignore')


a = np.array([1.0, 2.0, -3.0, 0.0])
b = np.array([0.0, 1.0, 0.0, 0.0])
c = a/b

print(c)

[ inf   2. -inf  nan]


In [32]:
# 배열 생성
a = np.zeros((5, 1)) #a = [0., 0., 0., 0., 0.]
print(a)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]
