In [41]:
import pandas as pd

s = pd.Series([[9904312, 3448737, 2890451, 2466052]]) 
print(s)
s = pd.Series([9904312, 3448737, 2890451, 2466052], index=["Seoul", "Busan", "Incheon", "Daegu"]) 
print(s)

0    [9904312, 3448737, 2890451, 2466052]
dtype: object
Seoul      9904312
Busan      3448737
Incheon    2890451
Daegu      2466052
dtype: int64


In [43]:
print(s.iloc[1], s["Busan"])

3448737 3448737


In [45]:
import pandas as pd
s2 = pd.Series({"Seoul": 9631482, "Busan": 3393191, "Incheon": 2632035, "Daegu": 1490158})

In [47]:
s

Seoul      9904312
Busan      3448737
Incheon    2890451
Daegu      2466052
dtype: int64

In [49]:
s2

Seoul      9631482
Busan      3393191
Incheon    2632035
Daegu      1490158
dtype: int64

In [51]:
ds = s - s2
ds

Seoul      272830
Busan       55546
Incheon    258416
Daegu      975894
dtype: int64

In [53]:
type(s.values)

numpy.ndarray

In [55]:
s.values

array([9904312, 3448737, 2890451, 2466052])

In [57]:
type(s2.values)

numpy.ndarray

In [59]:
s.values - s2.values

array([272830,  55546, 258416, 975894])

In [61]:
ds = s - s2
ds

Seoul      272830
Busan       55546
Incheon    258416
Daegu      975894
dtype: int64

In [63]:
ds.notnull()

Seoul      True
Busan      True
Incheon    True
Daegu      True
dtype: bool

In [65]:
rs = (s - s2)/s2*100
rs

Seoul       2.832690
Busan       1.636984
Incheon     9.818107
Daegu      65.489297
dtype: float64

In [67]:
rs = rs[rs.notnull()]
rs

Seoul       2.832690
Busan       1.636984
Incheon     9.818107
Daegu      65.489297
dtype: float64

In [69]:
rs["Busan"] = 1.63
rs

Seoul       2.832690
Busan       1.630000
Incheon     9.818107
Daegu      65.489297
dtype: float64

In [71]:
rs["Daegu"] = 1.41
rs

Seoul      2.832690
Busan      1.630000
Incheon    9.818107
Daegu      1.410000
dtype: float64

In [73]:
del rs["Seoul"]
rs

Busan      1.630000
Incheon    9.818107
Daegu      1.410000
dtype: float64

In [75]:
data = [['John', 28, 'Male'],
        ['Kate', 23, 'Female'],
        ['David', 31, 'Male'],
        ['Emily', 27, 'Female']]
columns = ['Name', 'Age', 'Gender']
df = pd.DataFrame(data, columns=columns)

print(df)

    Name  Age  Gender
0   John   28    Male
1   Kate   23  Female
2  David   31    Male
3  Emily   27  Female


In [77]:
print(df.values)
print(df.columns)
print(df.index)

[['John' 28 'Male']
 ['Kate' 23 'Female']
 ['David' 31 'Male']
 ['Emily' 27 'Female']]
Index(['Name', 'Age', 'Gender'], dtype='object')
RangeIndex(start=0, stop=4, step=1)


In [79]:
print(type(df.values))
print(type(df.columns))
print(type(df.index))

<class 'numpy.ndarray'>
<class 'pandas.core.indexes.base.Index'>
<class 'pandas.core.indexes.range.RangeIndex'>


In [81]:
print(df)

    Name  Age  Gender
0   John   28    Male
1   Kate   23  Female
2  David   31    Male
3  Emily   27  Female


In [83]:
data = {
    "2015": [9904312, 3448737, 2890451, 2466052],
    "2010": [9631482, 3393191, 2632035, 2431774],
    "2005": [9762546, 3512547, 2517680, 2456016],
    "2000": [9853972, 3655437, 2466338, 2473990],
    "지역": ["Capital", "Rural", "Capital", "Rural"],
    "2010-2015 Growth Rate": [0.0283, 0.0163, 0.0982, 0.0141]
}
columns = ["Areas", "2015", "2010", "2005", "2000", "2010-2015 Growth Rate"]
index = ["Seoul", "Busan", "Incheon", "Daegu"]
df = pd.DataFrame(data, index=index, columns=columns)
print(df)
df

        Areas     2015     2010     2005     2000  2010-2015 Growth Rate
Seoul     NaN  9904312  9631482  9762546  9853972                 0.0283
Busan     NaN  3448737  3393191  3512547  3655437                 0.0163
Incheon   NaN  2890451  2632035  2517680  2466338                 0.0982
Daegu     NaN  2466052  2431774  2456016  2473990                 0.0141


Areas     2015     2010     2005     2000  2010-2015 Growth Rate
Seoul     NaN  9904312  9631482  9762546  9853972                 0.0283
Busan     NaN  3448737  3393191  3512547  3655437                 0.0163
Incheon   NaN  2890451  2632035  2517680  2466338                 0.0982
Daegu     NaN  2466052  2431774  2456016  2473990                 0.0141

In [89]:
df.values

array([[nan, 9904312, 9631482, 9762546, 9853972, 0.0283],
       [nan, 3448737, 3393191, 3512547, 3655437, 0.0163],
       [nan, 2890451, 2632035, 2517680, 2466338, 0.0982],
       [nan, 2466052, 2431774, 2456016, 2473990, 0.0141]], dtype=object)

In [91]:
df.columns

Index(['Areas', '2015', '2010', '2005', '2000', '2010-2015 Growth Rate'], dtype='object')

In [93]:
df.index

Index(['Seoul', 'Busan', 'Incheon', 'Daegu'], dtype='object')

In [95]:
df.index.name = "Place"
df.columns.name = "Characteristics"

In [97]:
import pandas as pd

grade = {
    "Literature": [100, 80, 70, 90, 90],
    "Math": [70, 60, 100, 80, 90],
    "English": [80, 50, 90, 80, 90],
    "Society": [90, 90, 70, 60, 80],
    "Science": [100, 80, 70, 80, 90],
}

name = ["Abraham", "Bery", "Charlie", "David", "Eve"]
index = ["Literature", "Math", "English", "Society", "Science"]

df1 = pd.DataFrame(grade, columns=index, index=name)
df1

Literature  Math  English  Society  Science
Abraham         100    70       80       90      100
Bery             80    60       50       90       80
Charlie          70   100       90       70       70
David            90    80       80       60       80
Eve              90    90       90       80       90

In [99]:
import pandas as pd

data = {
    "Name": ["Frank", "Grok", "Hailey", "Isaac", "Jacob"],
    "Literature": [95, 90, 85, 93, 87],
    "English": [90, 87, 93, 94, 89],
    "Math": [73, 95, 87, 89, 93],
}

columns = ["Name", "Literature", "English", "Math"]
index = ["1", "2", "3", "4", "5"]

df_ex = pd.DataFrame(data, index=index, columns=columns)
print(df_ex)
df_ex['Avg'] = (df_ex['Literature'] + df_ex['English'] + df_ex['Math'])/3
df_ex['Avg'] = df_ex['Avg'].round(2)  # 각 행의 평균을 계산하고 소수점 두 자리로 반올림
print(df_ex)

     Name  Literature  English  Math
1   Frank          95       90    73
2    Grok          90       87    95
3  Hailey          85       93    87
4   Isaac          93       94    89
5   Jacob          87       89    93
     Name  Literature  English  Math    Avg
1   Frank          95       90    73  86.00
2    Grok          90       87    95  90.67
3  Hailey          85       93    87  88.33
4   Isaac          93       94    89  92.00
5   Jacob          87       89    93  89.67
